{
 "title": "Anomaly Detection Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Prediction Output",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "g_prediction_output", "legendFormat": "Prediction output" }
   ]
  },
  {
   "title": "Model Scoring",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(h_prediction_output_sum[30s]))/sum(increase(h_prediction_output_count[30s]))",
     "legendFormat": "Prediction Output"
    },
    {
     "expr": "sum(increase(h_prediction_score_sum[30s]))/sum(increase(h_prediction_score_count[30s]))",
     "legendFormat": "Prediction Scoring"
    }
   ]
  },
  {
   "title": "Service Request Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(c_prediction_total[5m])", "legendFormat": "Predict" },
    {
     "expr": "rate(c_model_information_total[5m])",
     "legendFormat": "ModelInfo"
    }
   ]
  },
  {
   "title": "Prediction Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "h_prediction_latency_sum", "legendFormat": "Prediction Latency" }
   ]
  }
 ]
}